import React from 'react';
import './Cards.css';
import CardItem from './CardItem';

function Cards() {
  return (
    <div className='cards'>
      <h1>Check out these Trending Tools!</h1>
      <div className='cards__container'>
        <div className='cards__wrapper'>
          <ul className='cards__items'>
            <CardItem
              src='images/img-9.jpg'
              text='Imagine Ai Art Generator'
              // label='Adventure'
              path='/Tools'
              
            />
            <CardItem
              src='images/img-2.jpg'
              text='MindGenie:AI revolution in task management'
              // label='Luxury'
              path='/Tools'
            />
          </ul>
          <ul className='cards__items'>
            <CardItem
              src='images/img-3.jpg'
              text='GoPDF: The all-in-one PDF solution. Edit, convert, and interact with your PDFs using advanced AI features'
              // label='Mystery'
              path='/Tools'
            />
            <CardItem
              src='images/img-4.jpg'
              text='InRoom AI:Interior Design Render Generated by AI'
              // label='Adventure'
              path='/Tools'
            />
            <CardItem
              src='images/img-8.jpg'
              text='Allclues Extension:Save links, text, images and notes to your Allclues.'
              // label='Adrenaline'
              path='/Tools'
            />
          </ul>
        </div>
      </div>
    </div>
  );
}

export default Cards;
